language: java
sudo: false
jdk:
- oraclejdk8
before_install: 
- chmod +x ./gradlew
install: travis_wait 100 ./gradlew setupCIWorkspace -S
script: 
"./gradlew jar"
- ls -la build/packages
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "build/packages/wiccan-*-Arts.jar"
  skip_cleanup: true
  on:
    tags: true