language: java
install: "./gradlew setupCIWorkspace"
script: "./gradlew jar"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "checksums.txt"
  - "build/libs/wiccan-*-Arts.jar"
  - "build/packages/wiccan-*-Arts.jar"
  skip_cleanup: true
  on:
    tags: true