language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
install: "./gradlew setupCIWorkspace"
script: 
- travis_wait 100 ./gradlew build
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  api_key: $GITHUB_OAUTH
  file: wiccanArts-1.10.2-*
  on:
    repo: Um-Mitternacht/Wiccan_Arts
    all_branches: true
    tags: true
